### ISSUE TITLE
Dinámicas del sistema

### ISSUE THREAD

**Issue by diespeso** [diespeso/crecimiento-urbano#2]
Actualmente las dinámicas del sistema que tenemos no reflejan las que se van a usar en el proyecto.

un ejemplo es que en se tiene la dinámica de "fenomenosNaturales", la cuál podríamos eliminar

y otro ejemplo como "restoVariable", de la cual no sabemos qué signifique.

- [ ] Investigar en la documentación de NetLogo qué son las dinámicas del sistema y como editarlas.

- [ ] Tratar de modificar las dinámicas del sistema para que se apeguen al proyecto actual.

**Comment by sofiamondaca** [comment]
Pues he estado viendo que onda con lo de la variable de "fenomenosnaturales" y veo que usualmente la utilizan como una tasa de "salida" de poblacion junto con la tasa de migracion. Ponle que el 

crecimiento poblacional = crecimiento natural (salidas y entradas de poblacion por nacimientos/muertes y fenomenos naturales) + crecimiento migratorio (salidas y entradas de poblacion por inmigracion/migracion)

Y pues como ya sabemos Tijuana es un destino mayor de migracion (mayormente por gente que quiere ir a USA pero se les niega y deben quedarse aqui), voy a suponer que de inmigracion tambien (no tengo los datos a la mano pero ando en eso)

Pero pues en Tijuana ya hace bastante tiempo que suceda algun fenomeno natural tan fuerte que cause fenomenos de inmigracion (si acaso algunos damnificados), por lo que considero que seria valido ignorar la variable "fenomenosnaturales" y simplemente no utilizarla

La variable "restoVariable" esa si no tengo idea y de lo que veo del codigo del programa no se si le podramos sacar mucho provecho, por lo que tambien propongo no utilizarla

Lo que podriamos hacer es: 

Nota: Debemos de tomar en cuenta que en el grafico del simulador sera a escala, osea que un punto equivaldra a miles ya que usualmente asi se miden las tasas de poblacion

1) Definir si utilizaremos un año en especifico para el simulador o utilizar un rango de años para medir el crecimiento de la poblacion (osea del 2015-2019 o no se) para hacer el modo "manual" que habiamos discutido donde el usuario pone las variables de las tasas de nacimiento/defuncion/migracion etc y para el modo "automatico" utilizamos variables ya definidas dependiendo del año

2) Investigar la poblacion total de Tijuana ya sea de: 1) cada año del rango que usaremos 2) solo del primer añp y calcular las demas (explicacion abajo) 

3) Aplicar esta formula para la tasa de crecimento poblacional (tengo entendido que esta debe ser anual, es decir, seran datos y una TCP diferente para cada año):

TCP en % = (% Natalicios  - % Defunciones) + (% Migraciones- %Inmigraciones)

4) Ya con la tasa de crecimiento poblacional y la poblacion total de un año en especifico, podemos aplicar una regla de 3 para calcular la poblacion final de ese mismo año y tal vez utilizarla como la poblacion total del año siguiente

Por ejemplo, si en 2015 la poblacion total fue de 1000 y la poblacion total de 2016 fue de 1025, quiere decir que la TCP fue de 2.5%, porque (1000*2.5) /100 = 25, y asi sucesivamente

(Honestamente no creo que sea asi de sencillo, pero los datos de poblacion que se tienen de Tijuana son algo escasos en linea, tendremos que buscar)

5) Con los monitoreadores de Netlogo podremos hacer un seguimiento de
-Poblacion final (por año)
-Crecimiento aproximado (%)
-Crecimiento o decrecimiento de las variables de natalicios, defuncion, etc (%)

**TL; DR** 
Propongo ajustar las dinamicas del sistema para que se apeguen a nuestro proyecto, lo que incluye ignorar las variables de fenomenosnaturales y restoVariable y proponer las de la TCP, los años a utilizar, la poblacion final (que es la poblacion total despues de que se le aplica la TCP). Calcular la TCP con TCP en % = (% Natalicios  - % Defunciones) + (% Migraciones- %Inmigraciones) y la Poblacion final de cada año con Poblacion final = Poblacion total + (Poblacion total*TCP)/100

Abierta a otras opiniones, ideas, criticas etc

**Comment by diespeso** [comment]
ok, igual se haga lo que se haga se deben modificar las dinámicas del sistema, y quien tome el issue debe documentarse sobre como hacerlo.

estoy de acuerdo, y también con la fórmula.

El año sería el último año de censo, que creo que fue 2015? osea el último año con una población 

> los años a utilizar

debería ser indefinido, es hasta que le usuario le de go otra vez y ahí se detiene la simulación, en teoría. pero también podríamos poner un límite más lógico, unos 200 años?

a aparte, entonces cada generación de celulas se calcularía a un año, osea primera gen. 2015, segunda gen. 2016, y así?

**Comment by diespeso** [comment]
**pregunta: de donde sacaste la fórmula del crecimiento y como obtendríamos las variables que usa?**

> crecimiento poblacional = crecimiento natural (salidas y entradas de poblacion por nacimientos/muertes y fenomenos naturales) + crecimiento migratorio (salidas y entradas de poblacion por inmigracion/migracion)

**Comment by sofiamondaca** [comment]
> a aparte, entonces cada generación de celulas se calcularía a un año, osea primera gen. 2015, segunda gen. 2016, y así?

supondria que si porque usualmente asi se hacen en los censos tambien

> pregunta: de donde sacaste la fórmula del crecimiento y como obtendríamos las variables que usa?

La encontre de esta [pagina ](https://apuntesdedemografia.com/curso-de-demografia/temario/tema-3-crecimiento-y-estructura-de-la-poblacion/calculo-del-crecimiento-de-la-poblacion/), voy a suponer que como es pagina de demografia de poblacion y eso es confiable

**Comment by scmm00** [comment]
ah y lo de las variables, pues estoy viendo que en el INEGI tienen los datos de nacimientos y fallecimientos por año, todavia no estoy muy segura de las tasas de migracion o inmigracion

si por alguna razon se nos llegara a complicar la recopilacion de los datos, creo que tendriamos que extendernos de Tijuana a todo el pais

**Comment by sofiamondaca** [comment]
ah y lo de las variables, pues estoy viendo que en el INEGI tienen los datos de nacimientos y fallecimientos por año, todavia no estoy muy segura de las tasas de migracion o inmigracion

si por alguna razon se nos llegara a complicar la recopilacion de los datos, creo que tendriamos que extendernos de Tijuana a todo el pais

**Comment by diespeso** [comment]
Si, pero quier saber como se van a recalcular las variables de nacimientos y así? Porque no pueden ser siempre las mismas

**Comment by sofiamondaca** [comment]
*AVANCE 25/3*

-Modificado las dinamicas del sistema para que se adhieran a lo que necesitamos (las variables eliminadas fueron fenomenosNaturales y restoVariable)
-Falta buscar exactamente como utilizaremos las variables de la dinamica del sistema, ya que la formula del flujoPoblacion es: manchaUrbana + nacimientos - fallecimientos - migrantes + inmigrantes + poblacionTotal

poblacionTotal es un numero fijo, mientras que nacimiento, fallecimientos, etc son variables que cambian por los sliders

parece que la inclusion de manchaUrbana es como si fuera manchaUrbana+=manchaUrbana + el resto de la formula

Nota: Las dinamicas del sistema SI afectan al modelo, pero parece que los cambios realizados no afectan como trabaja el modelo y sigue funcionando correctamente
![image](https://user-images.githubusercontent.com/62130046/77597619-b18df900-6ebc-11ea-9ba3-a5901206c9e5.png)

**Comment by sofiamondaca** [comment]
*AVANCE 29/3*

-Modificado las dinamicas del sistema, posiblemente el diseño final
![image](https://user-images.githubusercontent.com/62130046/77865877-5d00bb80-71e5-11ea-9e82-43c4de7e8bae.png)

-Las variables de las tasas son "traducidas" a numeros para que puedan ser utilizadas con cantidades de poblacion. La formula en cuestion es (tasa * poblacionInicial) / 100

-Falta investigar cual es la relacion de las dinamicas del sistema y los modelos
