### ISSUE TITLE
Implementar Slope

### ISSUE THREAD

**Issue by diespeso** [diespeso/crecimiento-urbano#4]
- Revisar en la wiki y la página de SLEUTH qué es slope en caso de tener dudas.
- En caso de quere discutir algo, @ a alguien o todos.

Implementar usando patches de diferentes colores basándose en un mapa de altitud de la zona de Tijuana.

**Comment by ProfessionalGodin** [comment]
### Avance 25 de marzo de 2020 ###
**Implementación Slope**
Para implementar el Slope (elevación de terreno), estoy manejando en un archivo KML diseñado en Google Earth versión escritorio, polígonos de colores distintos para simbolizar rangos de elevación (la idea es implementar etiquetas en la interfaz como labels).

Se utilizarán las siguientes etiquetas:

- Ligera (80m-160m)
- Estándar (161m-250m)
- Elevada (251m- 400m)
- Muy elevada (400m en adelante)

Me baso en este mapa topográfico:
https://es-mx.topographic-map.com/maps/6cn7/Tijuana/

Las complicaciones fueron más que nada aprender a manejar archivos .shp y transformar de .kml a .shp

**Próximos avances (29 de marzo de 2020)**
Haber dibujado los polígonos correspondientes
Haber elegido los colores distintivos
Implementar en NetLogo el .shp creado

**Comment by ProfessionalGodin** [comment]
### **Avance 29 de marzo de 2020** ###
**Implementación Slope**

Ya se terminaron de dibujar los polígonos con la herramienta Google Earth, falta solamente pasar la serie de archivos de cada polígono (4 archivos .shp) e implementarlos en NetLogo con 4 variables vectores, ya que son colores distintos.

![image](https://user-images.githubusercontent.com/62129899/77864584-4dca3f80-71de-11ea-961d-a8a8fe06a6c9.png)

**Para el siguiente avance:**
- Demostrar ejemplo en NetLogo
- Esperar siguiente issue

**Comment by ProfessionalGodin** [comment]
### **Avance 3 de abril de 2020**
**Implementación de Slope **
Se logró la implementación del Slope de manera correcta, se utilizaron globals en vez de breeds, ya que puede manipular datos vectoriales y cargar archivos tipo shp. 

En este documento se implementan los polígonos transformados en formato .shp para utilizarlos con coordenadas vectoriales:
[Slope.txt](https://github.com/diespeso/crecimiento-urbano/files/4430420/Slope.txt)

Esta es la vista previa:
![image](https://user-images.githubusercontent.com/62129899/78413846-256f8600-75ce-11ea-9683-66cb0402ab0d.png)

Y concluye la implementación del Slope utilizando patches de diferentes colores.
