### ISSUE TITLE
Justificar la no implementación de Land Use

### ISSUE THREAD

**Issue by diespeso** [diespeso/crecimiento-urbano#5]
**PREFERENTEMENTE: HACER UNA PÁGINA EN LA WIKI PARA ESTE TEMA**

1. Investigar como hacer una nueva página en la wiki del proyecto.
2. Escribir porqué no se va a implementar esta parte de SLEUTH en nuestro proyecto.

**Comment by Armenta99** [comment]
### **Avance 25 de Marzo de 2020**
Teniendo en cuenta lo comentado por el equipo, decidí investigar el porcentaje de urbanización que existe en Tijuana para ver como es utilizada la tierra. Buscando entre los datos de la INEGI encontré que Tijuana esta urbanizada en un 96% lo cual acompañado de una imagen satelital de Tijuana, nos permitia justificar la conclusión a la que habíamos llegado de la implementación de Land use.
Toda la info la registre en una nueva pagina de la wiki.

### **Avance 29 de Marzo de 2020**
Acomodare la info, en donde debe de ir, e intentare buscar algo más de info para complementar, así como ver posibles errores.

**Comment by Armenta99** [comment]
### Avance 27 de Marzo de 2020

Acomodé la no implementación de Land Use de la wiki en la pagina de Entrada de Datos

**Comment by diespeso** [comment]
El issue se cierra porque ya se cumplió el objetivo del mismo
