### ISSUE TITLE
Implementar Urban

### ISSUE THREAD

**Issue by diespeso** [diespeso/crecimiento-urbano#6]
Usando patches de forma binaria. Es decir, especificando bloques donde donde hay desarrollo urbano y las zonas fuera de esos bloques son rurales / no urbanizadas.

Si hay dudas: leer la wiki o la página de SLEUTH.

**Comment by ArzolaG** [comment]
### Avance: 25 de marzo ### 
Investigación acerca de los parches. Cómo implementar parches a las zonas establecidas como urbanizadas y no urbanizadas.

**Comment by ArzolaG** [comment]
### Avance: 29 de marzo
**Implementar Urban**
Utilizando la herramienta de Google Earth Pro, crear el "modelo" de urbanización, utilizando 2 parches, urbanizado y no urbanizado. Se terminó el parche de no urbanizado y con ayuda de netlogo se "pintará" lo que resta del color urbanizado.
![Urban](https://user-images.githubusercontent.com/51772734/77864893-368c5180-71e0-11ea-94a2-8c437e8144da.png)

**Para el siguiente avance:**
Implementar el archivo .shp en netlogo y terminar de dibujar el parche urbanizado

**Comment by ArzolaG** [comment]
### Avance: 3 de abril
Se implementó la urbanización mediante un archivo ".shp" con polígonos resultantes de la zona urbanizada en Tijuana.
![Urban1](https://user-images.githubusercontent.com/51772734/78417399-6ffcfc80-75e6-11ea-979b-cb357b684029.PNG)
